Revert "ceph-ansible-pipeline: run all lvm tests against ceph@master"
This commit breaks all ceph-ansible testing when running job lvm_batch
on PRs.

Typical error:

```
STDERR:

Traceback (most recent call last):
  File "/sbin/ceph-volume", line 6, in <module>
    main.Volume()
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 37, in __init__
    self.main(self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 59, in newfunc
    return f(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 147, in main
    terminal.dispatch(self.mapper, subcommand_args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 182, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/main.py", line 40, in main
    terminal.dispatch(self.mapper, self.argv)
  File "/usr/lib/python2.7/site-packages/ceph_volume/terminal.py", line 182, in dispatch
    instance.main()
  File "/usr/lib/python2.7/site-packages/ceph_volume/decorators.py", line 16, in is_root
    return func(*a, **kw)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 282, in main
    self.report(args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 157, in report
    strategy = self._get_strategy(args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/batch.py", line 190, in _get_strategy
    return strategy(unused_devices, args)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 26, in __init__
    self.validate()
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/bluestore.py", line 76, in validate
    validators.no_lvm_membership(self.hdds)
  File "/usr/lib/python2.7/site-packages/ceph_volume/devices/lvm/strategies/validators.py", line 38, in no_lvm_membership
    raise RuntimeError(msg % device.abspath)
RuntimeError: Unable to use device, already a member of LVM: /dev/sdb
```

This reverts commit 4d4b33ccbf46184399228f43be089889c46efdab.